name: Revive
version: ${project.version}
main: revive.reviveplugin.Reviveplugin
authors: [LEGITZX]

commands:
  revive:
    description: Core Revive Command.
    usage: /revive
    permission: revive.admin